In [6]:
import torch
import numpy as np 
print(torch.__version__)

2.2.1


# 初始化，索引，切片，维度变化等

In [110]:
# 1.创建，初始化         列表，元组，直接写大部分情况都通用
# 1.1有明确的值例如列表，数组
# Tensor 和 tensor 的区别
x1 = torch.tensor([1,3])
x1 = torch.from_numpy(np.array([[1],[2]]))
print(x1)
print('==========')

# 1.2没有明确的值，例如全0，全1，随机数
#torch.ones((2,3)) torch.ones([2,3]) torch.ones(2,3) 都可以
x1 = torch.ones(2,3,5)
#torch.full((2,3),4) 和 torch.full([2,3],4) 都可以
x1 = torch.full((2,3),4)
x1 = torch.eye(2,5)
print(x1)
print('==========')

# 1.3划一块区域，但是给值
print(torch.empty(3,5))
print('==========')

# 1.4 标准正态分布和均匀分布(0-1)
print(torch.randn(5,1))
print(torch.rand(5,1))
# 1.5 1-9的整数的均匀分布
print(torch.randint(1,10,[5,1]))

tensor([[1],
        [2]], dtype=torch.int32)
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]])
tensor([[3.2199e-05, 7.9173e-43, 1.0000e+00, 1.0000e+00, 1.0000e+00],
        [1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00],
        [1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00]])
tensor([[-0.7430],
        [ 0.5931],
        [ 0.4765],
        [-0.6555],
        [-0.1487]])
tensor([[0.2861],
        [0.4898],
        [0.6414],
        [0.6103],
        [0.6389]])
tensor([[5],
        [5],
        [3],
        [1],
        [6]])


In [130]:
# 1.6 等差数列  一个是步长，一个是切出来的个数
print(torch.arange(0,10,5))
print(torch.linspace(0,10,5))
# 1.7 格式
'''
FloatTensor：包含32位浮点数的tensor。
DoubleTensor：包含64位浮点数的tensor。
HalfTensor：包含16位浮点数的tensor。

ByteTensor：包含8位无符号整数的tensor。
CharTensor：包含8位有符号整数的tensor。
ShortTensor：包含16位有符号整数的tensor。
IntTensor：包含32位有符号整数的tensor。
LongTensor：包含64位有符号整数的tensor。
'''
print(torch.FloatTensor([1,3]).dtype,torch.LongTensor((1,3)).dtype)
print(torch.Tensor([1,3]).dtype,'->',torch.tensor([1,3]).dtype)
# 1.8 转换格式
print(torch.Tensor([1,3]).to(torch.int64).dtype)

tensor([0, 5])
tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
torch.float32 torch.int64
torch.float32 -> torch.int64
torch.int64


In [185]:
#2.索引
x1 = torch.arange(119.1).reshape(2,3,4,5)
x1 = torch.arange(120).reshape(2,3,4,5)
x1 = torch.rand(4,3,28,28)
print(x1.shape)
# 第一张图片
print(x1[0].shape)
# 第一张图片的第一个通道
print(x1[0,0].shape)
# 第一张图片的第一个通道的第一行
print(x1[0,0,0].shape)
# 第一张图片的第一个通道的第一行第一列值
print(x1[0,0,0,0],x1[0,0,0,0].dtype,x1[0,0,0,0].shape)

#2.2 切片
# 第一张到第二张图片
print(x1[0:2].shape)
# 第一张到第二张图片的第一个通道到第三个通道
print(x1[0:2,:3].shape)
# 共28行，-5代表23，-5:25左闭右开那就是23 24 (似乎不能从后往前取)
print(x1[0:2,:,:,-10:-1:2].shape)
# 用...表示省略的冒号
print(x1[...,-10:-1:2].shape)
print(x1[2,...].shape)
print(x1[2].shape)

torch.Size([4, 3, 28, 28])
torch.Size([3, 28, 28])
torch.Size([28, 28])
torch.Size([28])
tensor(0.2839) torch.float32 torch.Size([])
torch.Size([2, 3, 28, 28])
torch.Size([2, 3, 28, 28])
torch.Size([2, 3, 28, 5])
torch.Size([4, 3, 28, 5])
torch.Size([3, 28, 28])
torch.Size([3, 28, 28])


In [200]:
# 3. 维度变化
x1 = torch.randn(4,1,28,28)
print(x1.shape)
# 展平
print(x1.reshape(4,784).shape)
# reshape 和 view 几乎一样，区别是reshape会创建新的变量，如果多次调用比较影响内存；
# view则是在原有的内存基础上操作，节省内存，但是警惕修改，新手容易改变原始内存但是忘记。所以推荐用reshape（浪费一点也没事）



torch.Size([4, 1, 28, 28])
torch.Size([4, 784])


In [212]:
# 3.2 关于插入或者删除一维度
x1 = torch.randn(1,3,1,7,1,8,1)
print(x1.shape)
# 插入维度
print(x1.unsqueeze(3).shape)
# 删除维度,没有参数输入则默认删除全部一维度的，输入的参数认为是第几维度，如果该维度不是1，则不会修改，不会报错
print(x1.squeeze().shape)
print(x1.squeeze(4).shape)


torch.Size([1, 3, 1, 7, 1, 8, 1])
torch.Size([1, 3, 1, 1, 7, 1, 8, 1])
torch.Size([3, 7, 8])
torch.Size([1, 3, 1, 7, 8, 1])


In [213]:
# 4.重复扩张
x1 = torch.randn(2,3)
print(x1.repeat(2,3).shape)

torch.Size([4, 9])


In [218]:
# 5.维度交换
# t()必须是二维
print(torch.randn(2,5).t().shape)

# 一次交换两个  0,1和1，0一样的
print(torch.randn(1,3,5).transpose(0,1).shape)
print(torch.randn(1,3,5).transpose(1,0).shape)

# 调整顺序  
print(torch.randn(1,3,5).permute(2,1,0).shape)

torch.Size([5, 2])
torch.Size([3, 1, 5])
torch.Size([3, 1, 5])
torch.Size([5, 3, 1])


# 广播机制

In [229]:
a = torch.randn(3,1)
b = torch.randn(1,4)
print(a)
print((a+b).shape)
#能广播，不一定能手动expand
print(b.expand_as(a))

tensor([[ 0.5615],
        [-2.3368],
        [-0.5857]])
torch.Size([3, 4])


RuntimeError: The expanded size of the tensor (1) must match the existing size (4) at non-singleton dimension 1.  Target sizes: [3, 1].  Tensor sizes: [1, 4]

# 拼接拆分

In [242]:
a = torch.randn(4,32,8)
b = torch.randn(5,32,8)
# cat 拼接,默认是第一维，不会产生新的维度，只会增加值
print(torch.cat([a,b],dim = 0).shape)

# stack 拼接,产生了新的维度去区分a，b;可以通过dim控制新加的维度在哪里
b = torch.randn(4,32,8)
print(torch.stack([a,b],dim = 2).shape)

torch.Size([9, 32, 8])
torch.Size([4, 32, 2, 8])


In [255]:
# 拆分，一般通过索引来拆
# split 默认第一个维度   返回值是列表 更灵活
_1,_2 = a.split([17,15],dim=1)
print(_1.shape)
print(_2.shape)
# chunk 平均分，其实和split差不多，split还能干跟多事情  返回值是元组
_1,_2 = a.chunk(2,dim=1)
print(_1.shape)
print(_2.shape)

torch.Size([4, 17, 8])
torch.Size([4, 15, 8])
torch.Size([4, 16, 8])
torch.Size([4, 16, 8])


# 数学运算

In [269]:
# 线性代数中的矩阵乘法  @ 和matmul一样
a = torch.randn(4,4)
b = torch.randn(4,4)
print(a @ b,(a @ b).shape,a.matmul(b).shape)
#哈达玛积 保证形状一样直接每个数和每个数相乘
a * b

tensor([[ 0.5090, -0.6345, -1.3535,  2.0995],
        [ 0.8193,  0.5941,  0.6109,  0.5633],
        [ 0.7911,  0.8714,  0.4251,  1.6769],
        [ 2.2145, -1.7836,  0.9237,  0.1002]]) torch.Size([4, 4]) torch.Size([4, 4])


tensor([[ 0.0534,  0.0045, -0.2588,  0.3932],
        [ 1.8882,  2.0330, -0.7434, -0.6472],
        [ 0.2641,  0.2667, -1.0224,  2.2177],
        [-0.2302, -0.0354,  0.3402, -0.6421]])

In [278]:
# log 和 ln 和 exp
print(a.log())
print(a.log2())
print(a.exp())
print(a.exp().clamp(0,1))

# 向下取整 floor  向上取整 ceil 四舍五入 round

tensor([[-1.7723,     nan,  0.3049,     nan],
        [ 0.1982,     nan,  0.1217,  0.4273],
        [-0.7382,     nan,  0.3830,  0.3714],
        [    nan, -0.5076, -0.8135,  0.7047]])
tensor([[-2.5569,     nan,  0.4399,     nan],
        [ 0.2860,     nan,  0.1756,  0.6165],
        [-1.0650,     nan,  0.5526,  0.5358],
        [    nan, -0.7323, -1.1736,  1.0167]])
tensor([[1.1852, 0.9938, 3.8827, 0.6098],
        [3.3847, 0.5013, 3.0940, 4.6329],
        [1.6128, 0.5233, 4.3349, 4.2622],
        [0.6701, 1.8256, 1.5579, 7.5632]])
tensor([[1.0000, 0.9938, 1.0000, 0.6098],
        [1.0000, 0.5013, 1.0000, 1.0000],
        [1.0000, 0.5233, 1.0000, 1.0000],
        [0.6701, 1.0000, 1.0000, 1.0000]])


# 属性统计

In [288]:
a = torch.Tensor([[1,3,5],[2,4,6]])
print(a)
print(a.max())
print(a.sum())
print(a.prod())
#最大值下标， 最小值下标  单个数字索引   没有告诉具体的位置  ；常用的话还是要告诉求行的最大，列的最大这样比较好
print(a.argmax())
print(a.argmin())
print('======')
print(a.argmax(dim=0))
print(a.argmin(dim=1))

tensor([[1., 3., 5.],
        [2., 4., 6.]])
tensor(6.)
tensor(21.)
tensor(720.)
tensor(5)
tensor(0)
tensor([1, 1, 1])
tensor([0, 0])


In [294]:
# 范数norm  默认的是第二范数，同时可以指定维度
print(a.norm(),a.norm(1),a.norm(2),a.norm(2,dim=0))

tensor(9.5394) tensor(21.) tensor(9.5394) tensor([2.2361, 5.0000, 7.8102])


In [306]:
# topk问题
print(a.topk(2,dim=0),'\n',a.topk(2,dim=1))

# 第二个小的值
print(a.kthvalue(2),a.kthvalue(2,dim=0))

torch.return_types.topk(
values=tensor([[2., 4., 6.],
        [1., 3., 5.]]),
indices=tensor([[1, 1, 1],
        [0, 0, 0]])) 
 torch.return_types.topk(
values=tensor([[5., 3.],
        [6., 4.]]),
indices=tensor([[2, 1],
        [2, 1]]))
torch.return_types.kthvalue(
values=tensor([3., 4.]),
indices=tensor([1, 1])) torch.return_types.kthvalue(
values=tensor([2., 4., 6.]),
indices=tensor([1, 1, 1]))
